### PR TITLE
Design Home Page

### PR DESCRIPTION
**Pull request by HammadSiddique**
### In this PR, I: 🎯

- Created a `Car` component.
- Add car reducer in store to get car's state.
- Display all the cars on the home page using a carousel.
- When the user clicks on a specific car, it redirects him to the car details page.

### CODE REVIEW

**Review by ha-manel — CHANGES_REQUESTED** [review]
# Hey @HammadSiddique 
The page looks awesome ✨ The design is so clean and smooth 🥇 

### Here are some notes:
- [x] I encountered an issue and I'm not sure why it was happening: some items' pictures were not showing
image

- [x] We can force the same height for all images to make the design look better and symmetric. Suggestion: we can use `min-height` in combination with `object-fit: cover` to achieve that, please try it and let me know how it goes 👍  
image

**Comment by HammadSiddique** [comment]
@ha-manel 

- I have implemented the requested changes.
- For error#1 (some pictures not displaying)
  - For me all the pictures are displaying, I even tried running the app on a different browser (Microsoft edge) and I had no issues.
- For error#2 (fix images height)
  - Thank you for suggesting the `min-height` and `object-fit` properties, they came in handy and I'd say that home page looks better now.
 
image

**Comment by ha-manel** [comment]
# STATUS: APPROVED ✔️ 
My bad, my database had some test records where the link was "test" instead of an actual link 😆 I'm sorry!
Great job, truly. It look great 💯

**Review by ha-manel — APPROVED** [review]
# STATUS: APPROVED ✔️ 
My bad, my database had some test records where the link was "test" instead of an actual link 😆 I'm sorry!
Great job, truly. It looks great 💯

**Pull request merged**
